spring:
  datasource:
    url: jdbc:mysql://123.57.148.29:3306/yida1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&rewriteBatchedStatements=TRUE
    username: root
    password: iswater
    driver-class-name: com.mysql.jdbc.Driver

logging:
 config: classpath:logback-prod.xml

img:
 #文件保存路径
  uploadPath: /var/yida/
  #返回给前端的访问路径
  visitPath: /static/imgs/
  #重命名图片前缀
  prefix: etar-
   #环境地址
  imgUrl: http://123.57.148.29

mqtt:
  host: tcp://yidasvr.zsxiaohe.com:1883
  clientid: backend-7004
  username: admin
  password: admin
  topic: topic1
  timeout: 3000
  keepalive: 2000

#EMQ Basic 认证
appid: 01d6f2d460b8a
appsecret: Mjg1NjE1MzYzNzI4MjUyMDI2ODg4MzAwOTE0MTI4MzIyNTG
#服务器地址
emq_server: http://yidasvr.zsxiaohe.com:18080
#接口地址
connect_url: /api/v3/connections/
route_url: /api/v3/routes/

server:
  port: 7003

